// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Belt_Debug = require("bs-platform/lib/js/belt_Debug.js");

Belt_Debug.setupChromeDebugger(/* () */0);

function insert(t, newValue) {
  if (t) {
    var right = t[2];
    var left = t[1];
    var value = t[0];
    if (newValue < value) {
      return /* Node */Block.simpleVariant("Node", [
                value,
                insert(left, newValue),
                right
              ]);
    } else if (newValue > value) {
      return /* Node */Block.simpleVariant("Node", [
                value,
                left,
                insert(right, newValue)
              ]);
    } else {
      return t;
    }
  } else {
    return /* Node */Block.simpleVariant("Node", [
              newValue,
              /* Empty */0,
              /* Empty */0
            ]);
  }
}

function make(arr) {
  return List.fold_left(insert, /* Empty */0, arr);
}

function sum(t) {
  if (t) {
    return (t[0] + sum(t[1]) | 0) + sum(t[2]) | 0;
  } else {
    return 0;
  }
}

var x = List.fold_left(insert, /* Empty */0, /* :: */Block.simpleVariant("::", [
        1,
        /* :: */Block.simpleVariant("::", [
            2,
            /* :: */Block.simpleVariant("::", [
                3,
                /* [] */0
              ])
          ])
      ]));

console.log(x);

exports.insert = insert;
exports.make = make;
exports.sum = sum;
exports.x = x;
/*  Not a pure module */
